YP 9th H/W!
SirGeorga/PlaylistMaker pull request #2
Opened 2023-05-31 20:26 UTC by SirGeorga

Первая попытка

2023-06-02 07:36 UTC, NoDopezzz requested changes

2023-06-02 07:36 UTC, NoDopezzz commented on app/src/main/java/com/example/playlistmaker/SearchActivity.kt
> +            override fun beforeTextChanged(s: CharSequence?, start: Int, count: Int, after: Int) {
⏫ Зачастую, чтобы избавиться от необходимости переопределения методов, которые мы не хотим использовать, можно создать интерфейс с дефолтной пустой реализацией этих методов.

Например, можно создать такой интерфейс:

```kotlin
private interface SimpleTextWatcher : TextWatcher {

        override fun afterTextChanged(s: Editable?) = Unit

        override fun beforeTextChanged(s: CharSequence?, start: Int, count: Int, after: Int) = Unit

        override fun onTextChanged(s: CharSequence?, start: Int, before: Int, count: Int) = Unit
    }

```

И в месте определения слушателя достаточно лишь переопределить только нужные методы.

💡 Также можно воспользоваться одним из следующих методов:

*`doOnTextChanged`,* `doBeforeTextChanged` или `doAfterTextChanged` с передачей лямбды, которые под капотом реализуют одну из функций интерфейса `TextWatcher`. Или же мы можем воспользоваться универсальным методом `addTextChangedListener` и передать лямбду для каждой реализации интерфейса.

2023-06-02 07:36 UTC, NoDopezzz commented on app/src/main/java/com/example/playlistmaker/SearchActivity.kt
> +    private fun clearButtonVisibility(s: CharSequence?): Int {
💡 ⏫ Для изменения видимости элемента на экране можно использовать `extension` `View.isVisible`:

- `View.isVisible = true` соответствует `View.visibility = View.VISIBLE`
- `View.isVisible = false` соответствует `View.visibility = View.GONE`

Таким образом изменение видимости кнопки можно представить в виде `clearButton.isVisible = !s.isNullOrEmpty()`

2023-06-02 07:36 UTC, NoDopezzz commented on app/src/main/java/com/example/playlistmaker/SettingsActivity.kt
> +            val supportIntent = Intent(Intent.ACTION_SENDTO)
⏫ Чтобы обращаться к одной переменной было проще, можно изменять ее внутри одной scope function - [`apply`](https://kotlinlang.org/docs/scope-functions.html#this)

2023-06-02 07:36 UTC, NoDopezzz commented on app/src/main/res/layout/activity_search.xml
> +                android:textSize="@dimen/settings_content_text_size_16sp"
⏫ Данный аттрибуты для текста тоже можно выделить в стили, что поможет сформировать удобную и поддерживаемую дизайн систему приложения.
Я бы посоветовал вынести только `textSize`, `fontFamily`,  `fontWeight`, `fontColor` и `fontColorHint`, т.к. именно эти параметры задают стиль текста вне зависимости от того, где он будет находится и для чего использоваться.

2023-06-02 07:36 UTC, NoDopezzz commented on app/src/main/res/values/strings.xml
> +    <string name="AndrPracticumLink">https://practicum.yandex.ru/android-developer/</string>
⏫ Лучше при нейминге ресурсов придерживаться одного стиля, либо camelCase, либо snake_case. Дело в том, что когда на большом проекте с большим количество разработчиков замечаешь, что стиль написания кода пестрит разными вариантами это начинает сбивать.

2023-06-02 07:36 UTC, NoDopezzz commented on app/src/main/res/layout/activity_search.xml
> +                android:fontFamily="@font/ys_display_medium"
⚠️ Судя по макетам fontFamily должен быть `ys_display_regular`

2023-06-02 07:36 UTC, NoDopezzz commented on app/src/main/res/layout/activity_search.xml
> +            android:id="@+id/search_bar_container"
⚠️ Обрати внимание на дизайн поля ввода для разных тем: светлой и темной. Они отличаются задним фоном и цветом кнопок.

Макеты:
<img width="632" alt="image" src="https://github.com/SirGeorga/PlaylistMaker/assets/56832972/e207f780-305a-44ee-a94a-8c37fba94a4d">

Приложение:
<img width="308" alt="image" src="https://github.com/SirGeorga/PlaylistMaker/assets/56832972/e34b0641-bc80-48ae-adfc-2ffadc56b5c9">

2023-06-02 19:31 UTC, SirGeorga commented
Спасибо за рекомендации! Пока постарался учесть те, на которые мне хватило сообразительности)) С остальным постараюсь разобраться, как нагоню отставание от когорты))

2023-06-03 15:07 UTC, NoDopezzz approved these changes

2023-06-10 10:04 UTC, merged