Sprint 15 #2
SirGeorga/PlaylistMaker pull request #8
Opened 2024-03-29 06:51 UTC by SirGeorga

Sprint 15 PlayerActivity переработана, структура проекта подготовлена к дальнейшему построению архитектуры

2024-03-30 18:35 UTC, SirGeorga commented
Попытался решить проблему лишнего коммита, вроде получилось. Теперь, если отобразить изменения по всем коммитам в пулл-реквесте отображаются изменения только 15 спринта, несмотря на то, что номинально присутствует и 14. Наставник заверил, что можно так оставить

2024-03-31 17:26 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/ui/search/SearchHistory.kt
Магические числа лучше выносить в константы с говорящим названием

2024-03-31 17:26 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/ui/search/MediaAdapter.kt
> +    companion object {
companion обычно идёт в конце

Подробнее описано в [документации](https://kotlinlang.org/docs/coding-conventions.html#class-layout)

2024-03-31 17:27 UTC, DmitrijEgorow commented
Зачем остался [этот пустой файл](https://github.com/SirGeorga/PlaylistMaker/blob/d7f9f5402fad369ec62503697edf454ae09ba94b/app/src/main/java/com/example/playlistmaker/PlayerActivity.kt)?

2024-03-31 17:28 UTC, DmitrijEgorow commented
Цвет свитча должен быть другим – зеленый не входит в цветовую палитру приложения
![Screenshot_20240331_201224](https://github.com/SirGeorga/PlaylistMaker/assets/36837067/18fe4682-fce5-48ff-a942-09516137ace8)

2024-03-31 18:01 UTC, DmitrijEgorow requested changes

2024-03-31 18:01 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/domain/api/PlayerInteractor.kt
> +import android.os.Handler
domain слой никогда не зависит от классов Android, нужно убрать эти зависимости из интерактора

2024-03-31 18:01 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/domain/impl/PlayerInteractorImpl.kt
> +    private val tvElapsedTime: TextView
Не нужно передавать объекты View (которые относятся к presentation) в domain слой, работаем с View в активностях/фрагментах/...
это нужно будет исправить

2024-03-31 18:01 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/data/network/RetrtofitNetworkClient.kt
> +class RetrtofitNetworkClient : NetworkClient {
typo

2024-03-31 18:01 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/domain/api/PlayerInteractor.kt
> +    fun startPlayer()
Нарушается правило зависимостей
Интерактор знает о Handler, MediaPLayer и хранит состояние

2024-04-05 08:28 UTC, merged